// Generated by CoffeeScript 1.6.2
(function() {
  var setupWorld;

  goog.provide('game');

  goog.require('lime.Director');

  goog.require('lime.Scene');

  goog.require('lime.Layer');

  goog.require('lime.Circle');

  goog.require('lime.Label');

  goog.require('lime.animation.Spawn');

  goog.require('lime.animation.FadeTo');

  goog.require('lime.animation.ScaleTo');

  goog.require('lime.animation.MoveTo');

  goog.require('lime.transitions.SlideInRight');

  goog.require('lime.transitions.Dissolve');

  goog.require('box2d.BodyDef');

  goog.require('box2d.BoxDef');

  goog.require('box2d.CircleDef');

  goog.require('box2d.CircleShape');

  goog.require('box2d.PolyDef');

  goog.require('box2d.Vec2');

  goog.require('box2d.JointDef');

  goog.require('box2d.MouseJointDef');

  goog.require('box2d.World');

  goog.require('game.TitleScreen');

  goog.require('game.GameScene');

  goog.require('game.Player');

  game.start = function() {
    lime.scheduleManager.setDisplayRate(1000 / 60);
    game.director = new lime.Director(document.body, 1024, 768);
    game.world = setupWorld();
    return game.titleScreen();
  };

  setupWorld = function() {
    var bounds, gravity;

    gravity = new box2d.Vec2(0, 200);
    bounds = new box2d.AABB();
    bounds.minVertex.Set(-1024, -768);
    bounds.maxVertex.Set(2 * 1024, 2 * 768);
    return new box2d.World(bounds, gravity, false);
  };

  game.switchScene = function(sceneContents, transition, duration) {
    var layer, scene;

    scene = new lime.Scene();
    layer = new lime.Layer();
    scene.appendChild(layer);
    layer.appendChild(sceneContents);
    return game.director.replaceScene(scene, transition, duration);
  };

  game.titleScreen = function() {
    return game.switchScene(new game.TitleScreen(), lime.transitions.Dissolve, .5);
  };

  game.startGame = function(mode) {
    return game.switchScene(new game.GameScene(), lime.transitions.SlideInRight, 1);
  };

  goog.exportSymbol('game.start', game.start);

}).call(this);
