// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  goog.provide('game.Player');

  goog.require('game');

  goog.require('lime.Sprite');

  goog.require('game.Object');

  game.Player = (function(_super) {
    __extends(Player, _super);

    function Player(options) {
      Player.__super__.constructor.call(this, options);
      this._shape.setFill(0, 100, 0);
    }

    return Player;

  })(game.Object);

}).call(this);
