// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  goog.provide('game.TitleScreen');

  goog.require('lime.Circle');

  game.TitleScreen = (function(_super) {
    __extends(TitleScreen, _super);

    function TitleScreen() {
      lime.Sprite.call(this);
      this.draw();
      console.log('hello');
    }

    TitleScreen.prototype.draw = function() {
      var shape;

      shape = new lime.Circle();
      shape.setSize(700, 200);
      return shape.setFill(255, 150, 0);
    };

    return TitleScreen;

  })(lime.Sprite);

}).call(this);
