// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  goog.provide('game.TitleScreen');

  goog.require('lime.RoundedRect');

  game.TitleScreen = (function(_super) {
    __extends(TitleScreen, _super);

    function TitleScreen() {
      lime.Sprite.call(this);
      this.draw();
    }

    TitleScreen.prototype.draw = function() {
      var amount, base, newBase, num, shape, _i, _results;

      amount = 10;
      base = 900;
      _results = [];
      for (num = _i = amount; amount <= 1 ? _i <= 1 : _i >= 1; num = amount <= 1 ? ++_i : --_i) {
        newBase = base - Math.sqrt(num) * 270;
        console.log(newBase);
        shape = new lime.RoundedRect();
        shape.setSize(newBase, 50);
        shape.setFill(33, 55, 45);
        shape.setPosition(512, 775 - (718 / amount * num));
        shape.setPosition;
        _results.push(this.appendChild(shape));
      }
      return _results;
    };

    return TitleScreen;

  })(lime.Sprite);

}).call(this);
